### ISSUE TITLE
XInput injection question

### ISSUE THREAD

**Issue by evilC** [r57zone/X360Advance#1]
Hi, I was wondering if the XInput injection technique you use here can be used with other projects.
ie would it be possible to inject an axis from a standard HID (DirectInput) joystick into the XI controller?
Also same applies for buttons
The reason I ask is that I write a remapping app ([UCR](https://github.com/Snoothy/UCR)) which is capable of creating virtual XInput controllers (Using ViGEm) but obviously it cannot alter how a game sees a physical XI controller.
So it would be kind of cool if people could eg output to a vJoy virtual DI controller, then use your injector to inject some axes / buttons from the vJoy stick into the physical XI device.
Yeah, there's X360ce, but AFAIK this uses "Method 2" (Placing DLL into game folder), I wondered if your injector might be a better alternative

**Comment by r57zone** [comment]
Hi, DirectInput is not supported, but reading from Arduino is supported. Currently, only changing the axis of the left stick for driving is supported, depending on the tilt of the gyroscope.
For some special ways with DirectInput, need probably tweak the [xinput inject library](https://github.com/r57zone/X360Advance/blob/master/XInputInject/XInputInject.cpp) a little and compile another dlls.

**Comment by r57zone** [comment]
[This project](https://www.worldofjoysticks.com/) seems to be able to read dinput and combine it with xinput.
