### ISSUE TITLE
Question on USB dongle orientation

### ISSUE THREAD

**Issue by fvig2001** [r57zone/X360Advance#2]
Hi

I am thinking of using this on 2 devices but their setups are a bit different. 1 has the usb port upside down and another is the usb is at the top of the device (USB device will be vertical). Will this work for both devices assuming I copy the calibration data correctly?

I plan to port/modify the code to fit a smaller arduino that is directly plugged to the USB port but worst case, I might put the arduino inside the device that has it vertically as there is space for an internal usb drive but it will still be vertical..

**Comment by r57zone** [comment]
Hi, yes, I think this will work. If the axes are inverted, then you can invert them in the code.
